### ISSUE TITLE
Current conda environment causes incompatibility between gdal and pdal / python-pdal

### ISSUE THREAD

**Issue by bhoefle-3dgeo** [ssciwr/afwizard#330] opened 2022-04-05 16:25 UTC
**Problem**
In the current conda environment definition in [environment.yml](https://github.com/ssciwr/adaptivefiltering/blob/main/environment.yml) defines fixed versions of `pdal`and `python-pdal` whereas the version of `gdal` is not fixed. This currently causes dll issues on Windows, even just running gdal e.g. `python -c "import osgeo"`.  It seems that the PDAL installation crashes the GDAL installation (similar to what is described [here](https://github.com/conda-forge/gdal-feedstock/issues/541)). 

When installing `pdal` and `python-pdal` without fixed version, gdal works. This leads - at the minute - to the installation of  
```
gdal 3.4.2
pdal 2.4.0
python-pdal 3.1.2
```
This seems to work. However, the current code of `adaptivefiltering` is not working with the newest `python-pdal` version. Parameters of functions seem to have changed compared to the hardcoded versions in the current environment.yml.

**Possible solution**

- [ ] Update environment.yml to support newest versions of gdal, pdal and python-pdal.
- [ ] Update all codes using pdal/python-pdal to the newest version.
- [ ] Implement test routine during package installation to check whether gdal/pdal etc. installation is running and if not, point to solution.

**Comment by bhoefle-3dgeo** [comment] 2022-04-05 16:37
Further observation. With python 3.8 (3.8.13) the jupyter lab starts and codes are working until the point where pdal functions are used. With the lastest python 3.9 the jupyter lab is crashing.

**Comment by lkeegan** [comment] 2022-04-06 09:55
Reproduced on windows CI:
- https://github.com/ssciwr/adaptivefiltering/runs/5839876798?check_suite_focus=true
```
ImportError while loading conftest 'D:\a\adaptivefiltering\adaptivefiltering\tests\conftest.py'.
tests\conftest.py:1: in <module>
    import adaptivefiltering
adaptivefiltering\__init__.py:8: in <module>
    import adaptivefiltering.lastools
adaptivefiltering\lastools.py:1: in <module>
    from adaptivefiltering.dataset import DataSet
adaptivefiltering\dataset.py:9: in <module>
    from adaptivefiltering.visualization import visualization_dispatcher
adaptivefiltering\visualization.py:3: in <module>
    from osgeo import gdal
C:\Miniconda\envs\adaptivefiltering\lib\site-packages\osgeo\__init__.py:45: in <module>
    _gdal = swig_import_helper()
C:\Miniconda\envs\adaptivefiltering\lib\site-packages\osgeo\__init__.py:41: in swig_import_helper
    raise ImportError(traceback_string + '\n' + msg)
E   ImportError: Traceback (most recent call last):
E     File "C:\Miniconda\envs\adaptivefiltering\lib\site-packages\osgeo\__init__.py", line 29, in swig_import_helper
E       return importlib.import_module(mname)
E     File "C:\Miniconda\envs\adaptivefiltering\lib\importlib\__init__.py", line 127, in import_module
E       return _bootstrap._gcd_import(name[level:], package, level)
E     File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
E     File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
E     File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
E     File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
E     File "<frozen importlib._bootstrap>", line 565, in module_from_spec
E     File "<frozen importlib._bootstrap_external>", line [11](https://github.com/ssciwr/adaptivefiltering/runs/5839876798?check_suite_focus=true#step:12:11)73, in create_module
E     File "<frozen importlib._bootstrap>", line [22](https://github.com/ssciwr/adaptivefiltering/runs/5839876798?check_suite_focus=true#step:12:22)8, in _call_with_frames_removed
E   ImportError: DLL load failed while importing _gdal: The specified procedure could not be found.
```
Pinning gdal version in the conda environment (#331) as a short term fix for this issue:
- https://github.com/ssciwr/adaptivefiltering/runs/5848297148?check_suite_focus=true
- windows CI still fails but at a later (and I think unrelated) stage in the test suite

**Comment by bhoefle-3dgeo** [comment] 2022-04-06 10:01
After quick testing it seems to be a fix. GDAL is running and also the Jupyter Lab Notebook I have tested is running and showing GDAL outputs.

**Comment by dokempf** [comment] 2022-06-10 11:38
I think (or hope) #358 has finally resolved this correctly by removing the reason for the partial pins between GDAL and PDAL(-python).

**Closed by dokempf** 2022-06-10 11:38 UTC
